
export interface IAppConfig {
  PORT: number;
  MONGO_URL: string;
  ADMIN_USER_ACCESS_TOKEN_EXP_TIME: string;
  ADMIN_USER_REFRESH_TOKEN_EXP_TIME: string;
  ADMIN_USERNAME: string;
  ADMIN_EMAIL: string;
  ADMIN_PASSWORD: string;
  ADMIN_ACCESS_TOKEN_JWT_SECRET: string;
  ADMIN_REFRESH_TOKEN_JWT_SECRET: string;
  USER_ACCESS_TOKEN_JWT_SECRET: string;
  USER_REFRESH_TOKEN_JWT_SECRET: string;
  USER_ACCESS_TOKEN_EXP_TIME: string;
  USER_REFRESH_TOKEN_EXP_TIME: string;
  SUPABASE_URL: string;
  SUPABASE_KEY: string;
  SUPABASE_BUCKET: string;
}
