import { IAppConfig } from 'src/interface/config';

export default (): IAppConfig => ({
  PORT: parseInt(process.env.PORT, 10) || 3000,
  MONGO_URL: process.env.MONGO_URL,
  ADMIN_USER_ACCESS_TOKEN_EXP_TIME:
    process.env.ADMIN_USER_ACCESS_TOKEN_EXP_TIME,
  ADMIN_USER_REFRESH_TOKEN_EXP_TIME:
    process.env.ADMIN_USER_REFRESH_TOKEN_EXP_TIME,
  ADMIN_EMAIL: process.env.ADMIN_EMAIL,
  ADMIN_USERNAME: process.env.ADMIN_USERNAME,
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
  ADMIN_ACCESS_TOKEN_JWT_SECRET: process.env.ADMIN_ACCESS_TOKEN_SECRET,
  ADMIN_REFRESH_TOKEN_JWT_SECRET: process.env.ADMIN_REFRESH_TOKEN_JWT_SECRET,
  USER_ACCESS_TOKEN_JWT_SECRET: process.env.USER_ACCESS_TOKEN_JWT_SECRET,
  USER_REFRESH_TOKEN_JWT_SECRET: process.env.USER_ACCESS_TOKEN_JWT_SECRET,
  USER_ACCESS_TOKEN_EXP_TIME: process.env.USER_ACCESS_TOKEN_EXP_TIME,
  USER_REFRESH_TOKEN_EXP_TIME: process.env.USER_REFRESH_TOKEN_EXP_TIME,
  SUPABASE_URL: process.env.SUPABASE_URL,
  SUPABASE_KEY: process.env.SUPABASE_KEY,
  SUPABASE_BUCKET: process.env.SUPABASE_BUCKET,
});
